// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wqwNKHg2tfo2ObQPG_utePVmEvwuFUs',
    appId: '1:361894008686:web:958aff1cfff12df5ed537f',
    messagingSenderId: '361894008686',
    projectId: 'portfolio-37ee9',
    authDomain: 'portfolio-37ee9.firebaseapp.com',
    storageBucket: 'portfolio-37ee9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1V5_zmQBevnha6Vv3aHDWQWLqr8AE8fs',
    appId: '1:361894008686:android:d8a663c172a5a32eed537f',
    messagingSenderId: '361894008686',
    projectId: 'portfolio-37ee9',
    storageBucket: 'portfolio-37ee9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRwZdXq1IolAD24ajRUP2p5fn8AH3CVU',
    appId: '1:361894008686:ios:8e4ce4d17908e90fed537f',
    messagingSenderId: '361894008686',
    projectId: 'portfolio-37ee9',
    storageBucket: 'portfolio-37ee9.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRwZdXq1IolAD24ajRUP2p5fn8AH3CVU',
    appId: '1:361894008686:ios:8e4ce4d17908e90fed537f',
    messagingSenderId: '361894008686',
    projectId: 'portfolio-37ee9',
    storageBucket: 'portfolio-37ee9.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3wqwNKHg2tfo2ObQPG_utePVmEvwuFUs',
    appId: '1:361894008686:web:b07616550a6b07ebed537f',
    messagingSenderId: '361894008686',
    projectId: 'portfolio-37ee9',
    authDomain: 'portfolio-37ee9.firebaseapp.com',
    storageBucket: 'portfolio-37ee9.firebasestorage.app',
  );
}
